name: ci

on: pull_request

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Enable Corepack
        run: corepack enable

      - name: Install Node dependencies
        run: |
          yarn install

      - name: Compile Sass (sanity check)
        run: ./node_modules/.bin/sass --no-source-map --load-path=node_modules --load-path=src src/css/App.scss /tmp/app.css

      - name: Lint the source code
        run: yarn run lint

      - name: Run front-end unit tests
        run: yarn run test

      - name: Update Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install webfonts
        run: |
          ./scripts/fonts.sh

      - name: Start local website server
        run: |
          yarn start &
          sleep 5

      - name: Run browser tests
        run: yarn run cypress run
